### ISSUE TITLE
how to set toc as your demo

### ISSUE THREAD

**Issue by Lincoln12w** [tzvetkov75/solar-theme-hexo#1]
I'm new to hexo, found your theme on the theme page and very like it. But when I run server on my laptop, I cannot see the TOC on the sidebar as your demo, and I cannot found any place to config. Am I miss something?

**Comment by Lincoln12w** [comment]
And the how to change the highlight mode to your demo's, I pretty like that. Thanks for the beauty theme.

**Comment by Lincoln12w** [comment]
When I deploy with github pages, things going weird. Can you visit lincoln12w.github.io and tell what I miss.

**Comment by tzvetkov75** [comment]
Hi Lincoln12w :-) the TOC is displayed if there is enough space in right border for the headers. Is is dynamic behavior (see when  resizing the screen). 
The TOC element on you page are there, but not displayed.  It seems bug, I will investigate. Can you try with very simple blog?

Regarding highlighting , see in the _config.yml the parameter  `highlight: railscasts`, I used for the demo `highlight: lightcode`  , all possible values are in listed https://github.com/tzvetkov75/solar-theme-hexo/tree/master/source/css/_highlight
thanks

**Comment by Lincoln12w** [comment]
Thanks for answering, I have just test with a simple blog as you suggested, but the TOC still missing. Do I need to post my config?

**Comment by tzvetkov75** [comment]
I fond the problem and fix it. Please, that the latest version :-)
The problem was  when using  heading level 1 `#  Title`. Most of the user use level 2 `## head` onwards.
Tell me if it work for you as expected

**Comment by Lincoln12w** [comment]
It works, thanks!

**Comment by tzvetkov75** [comment]
cool :-)
