### ISSUE TITLE
Side TOC doesn't wrap

### ISSUE THREAD

**Issue by digitalap3** [tzvetkov75/solar-theme-hexo#5]
Thank you for this beautiful theme.  I am having an odd issue where the text for the headings in the toc sidebar on the post page does not wrap and instead overflows into the post itself. 

Thanks again.

**Comment by tzvetkov75** [comment]
Hi, 
thanks for reporting. I will fix it in the 1-2 days and let you know

**Comment by digitalap3** [comment]
Hey that's great thank you.  I figured it had more to do with cactus.

**Comment by tzvetkov75** [comment]
Hey, Just fixed it. 
Please try and let me know if it works for you. 
You need to make 'git pull' from solar folder with the repo and  regenerate 'hexo generate'

**Comment by digitalap3** [comment]
Fabulous!  I did have to end up just redownloading (maybe not necessary), then hexo clean and hexo generate.  It could have been an issue with something the previous theme was doing but it worked after that.  Thank you!
