### ISSUE TITLE
Why when I click the "Home" and "About" buttons it shows the 404 page?

### ISSUE THREAD

**Issue by PenchantLeo** [tzvetkov75/solar-theme-hexo#8]
Hi, tzvetkov,
I very appreciate that you can share this amazing theme with us. 
I'm still a rookie on this and I'm getting into trouble now. 
Why when I click the "Home" and "About" buttons it shows the 404 page?
Which file should I check out or modify with?

**Comment by PenchantLeo** [comment]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/100772419/156923618-2a5b15fe-bcb6-47ff-8998-7170a2ed3c65.png">

**Comment by PenchantLeo** [comment]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/100772419/156924247-893f3fd4-c1d4-49be-96ad-80b5c4d0c2b4.png">

**Comment by PenchantLeo** [comment]
> <img alt="image" width="562" src="https://user-images.githubusercontent.com/100772419/156923618-2a5b15fe-bcb6-47ff-8998-7170a2ed3c65.png">

I ran hexo s and check the 2 buttons on the local host and got warnings like this.

**Comment by PenchantLeo** [comment]
> <img alt="image" width="534" src="https://user-images.githubusercontent.com/100772419/156924247-893f3fd4-c1d4-49be-96ad-80b5c4d0c2b4.png">

And I open the "public" file and checked the index.html.

**Comment by tzvetkov75** [comment]
Hi PenchantLeo, 
thank you for using and enjoying  the theme.
1) Regarding the Home button. Open the Solar theme configuration file  typically under `themes/solar/_config.yml` point the right home at the beginning of the config
 ```
nav:
  Home: /
  About: /about/
  Writing: /archives/
```  
regenerate and restart the server 

2) Regarding the About link. You need to create an about page.  This is a page like every other but must be in right folder create the page in *sources/about/index.md* , like this 
```
mkdir sources/about
touch  source/about/index.md
```  

Please let me know if this solves the problem 

:-)

**Comment by PenchantLeo** [comment]
> touch  source/about/index.md

Thank you Mr. tzvetkov! 
Your ways REALLY HELPED!
I solved my issues with your methods just a couple of minutes ago. 
I'm already stuck on this for several days.
My clumsy English can't express my appreciation! 
Thank you so much again! 
Mercy!

**Comment by tzvetkov75** [comment]
enjoy
