### ISSUE TITLE
头像发亮问题

### ISSUE THREAD

**Issue by yydxss** [tzvetkov75/solar-theme-hexo#9]
鼠标一扫过就点亮，怎么才能让头像常亮呢？

**Comment by tzvetkov75** [comment]
Can you send me screenshot on issue  ?
你能把问题的截图发给我吗？

**Comment by yydxss** [comment]
感谢您的回复！不好意思，我提问的不太清楚，我详细的解释一下我遇到的问题：
一、这是我建立好的博客地址：https://blog-two-drab-13.vercel.app/ ，打开我的博客之后，可以看到主页的头像是灰色的，但是鼠标触碰头像，头像就会变为正常效果。我想要我的头像一直是正常效果，不想要鼠标触碰头像，它才能变为正常效果。
二、这是我在博客写的文章地址：https://blog-two-drab-13.vercel.app/2022/06/01/%E7%AC%AC%E4%B8%80%E7%AF%87%E6%96%87%E7%AB%A0/，打开这篇文章之后，可以看到日期之前的 JOHN DOE ，我想把这个名字换为我的名字。

总结：一、主页的头像默认情况下是灰色的，只有鼠标触碰之后，才会变成正常效果，如何省去这个步骤，让头像一直保持正常效果？
二、文章作者的名字，如何更改？

再次感谢您的回复，我是零基础搭建博客，对代码这块一头雾水，还望多多指教！

**Comment by yydxss** [comment]
Thank you for your reply. I can't upload screenshots here.Let me explain in detail the problems I have encountered.
一、This is my established blog address：https://blog-two-drab-13.vercel.app/ ，My homepage avatar is gray,But after the mouse touches it, it will become normal.I want to remove this step.I hope my avatar will always keep normal effect.How to do it?
二、This is the article I wrote in my blog：https://blog-two-drab-13.vercel.app/2022/06/01/%E7%AC%AC%E4%B8%80%E7%AF%87%E6%96%87%E7%AB%A0/，After opening, you can see the author's name "JOHN DOE" in front of the writing date of the article. I want to change "JOHN DOE" to my name.

Thank you again for your reply.

**Comment by yydxss** [comment]
Thank you for your reply. I can't upload screenshots here.Let me explain in detail the problems I have encountered.

This is my established blog address：https://blog-two-drab-13.vercel.app/ ，My homepage avatar is gray,But after the mouse touches it, it will become normal.I want to remove this step.I hope my avatar will always keep normal effect.
How to do it?

Thank you again for your reply.

**Comment by tzvetkov75** [comment]
Hi, 

Thanks, now I understand it. Find the file source/css/_partial/header.styl and delete (remove)  line 31 and 32 which set the grey color. Generate again your blog.

Here a link to first line 
https://github.com/tzvetkov75/solar-theme-hexo/blob/2518f2ace98218657eeba3e8f3f8cf06737cb2ab/source/css/_partial/header.styl#L31

Cheers

**Comment by yydxss** [comment]
HI,

The problem has been solved!!!
Thank you very much~~~

**Comment by tzvetkov75** [comment]
Happy to hear it. Please give a start if you like my work :-)
